configuration for "PIC18F2480" is
  shared label noFreeCh;
  shared label setid;
end configuration;
--
testbench for "PIC18F2480" is
begin
  test_timeout: process is
    begin
      wait for 2000 ms;
      report("flim_boot_init_test: TIMEOUT");
      report(PC); -- Crashes simulator, MDB will report current source line
      PC <= 0;
      wait;
    end process test_timeout;
    --
  flim_boot_init_test: process is
    type test_result is (pass, fail);
    variable test_state : test_result;
    begin
      report("flim_boot_init_test: START");
      test_state := pass;
      RA3 <= '1'; -- Setup button not pressed
      --
      RB4 <= '1'; -- DOLEARN off
      RA5 <= '1'; -- UNLEARN off
      --
      wait until PC == noFreeCh; -- Initialise event store
      report("flim_boot_init_test: Reached noFreeCh");
      --
      wait until PC == setid; -- FLiM setup
      report("flim_boot_init_test: Reached setid");
      --
      if test_state == pass then
        report("flim_boot_init_test: PASS");
      else
        report("flim_boot_init_test: FAIL");
        report(PC); -- Crashes simulator, MDB will report current source line
      end if;          
      PC <= 0;
      wait;
    end process flim_boot_init_test;
end testbench;
