configuration for "PIC18F2480" is
end configuration;
--
testbench for "PIC18F2480" is
begin
  test_timeout: process is
    begin
      wait for 3 ms;
      report("flim_module_id_test: TIMEOUT");
      PC <= 0;
      wait;
    end process test_timeout;
    --
  flim_module_id_test: process is
    type test_result is (pass, fail);
    variable test_state : test_result;
    variable module_id_index : integer;
    begin
      report("flim_module_id_test: START");
      test_state := pass;
      RA3 <= '1'; -- Setup button not pressed
      module_id_index := 3; -- Index of Module ID parameter
      --
      wait until RB6 == '1'; -- Booted into FLiM
      wait for 4 ic; -- Delay to avoid first message getting lost
      --
      RXB0D0 <= 16#73#;          -- RQNPN, CBUS read node parameter by index
      RXB0D1 <= 0;               -- NN high
      RXB0D2 <= 0;               -- NN low
      RXB0D3 <= module_id_index; -- Module ID parameter index
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      --
      wait on TXB1CON for 1 ms;
      if TXB1CON.TXREQ == '1' then
        report("flim_module_id_test: Unexpected response");
        test_state := fail;
      end if;
      --
      RXB0D0 <= 16#73#;          -- RQNPN, CBUS read node parameter by index
      RXB0D1 <= 4;               -- NN high
      RXB0D2 <= 2;               -- NN low
      RXB0D3 <= module_id_index; -- Module ID parameter index
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      --
      TXB1CON.TXREQ <= '0';
      wait until TXB1CON.TXREQ == '1';
      if TXB1D0 != 16#9B# then -- PARAN, CBUS individual parameter response
        report("flim_module_id_test: Sent wrong response");
        test_state := fail;
      end if;
      if TXB1D1 != 4 then
        report("flim_module_id_test: Sent wrong Node Number (high)");
        test_state := fail;
      end if;
      if TXB1D2 != 2 then
        report("flim_module_id_test: Sent wrong Node Number (low)");
        test_state := fail;
      end if;
      if TXB1D3 != module_id_index then
        report("flim_module_id_test: Sent wrong parameter index");
        test_state := fail;
      end if;
      if TXB1D4 != 8 then
        report("flim_module_id_test: Sent wrong parameter value");
        test_state := fail;
      end if;
      --
      if test_state == pass then
        report("flim_module_id_test: PASS");
      else
        report("flim_module_id_test: FAIL");
      end if;          
      PC <= 0;
      wait;
    end process flim_module_id_test;
end testbench;
