configuration for "PIC18F2480" is
  shared label _CANInit;
  shared label noFreeCh;
  shared label setid;
  shared label main0;
end configuration;
--
testbench for "PIC18F2480" is
begin
  test_timeout: process is
    begin
      wait for 2000 ms;
      report("flim_setup_events_test: TIMEOUT");
      report(PC); -- Crashes simulator, MDB will report current source line
      PC <= 0;
      wait;
    end process test_timeout;
    --
  flim_setup_events_test: process is
    type test_result is (pass, fail);
    variable test_state : test_result;
    begin
      report("flim_setup_events_test: START");
      test_state := pass;
      --
      RB4 <= '1'; -- DOLEARN off
      RA5 <= '1'; -- UNLEARN off
      --
      wait until PC == _CANInit;
      report("flim_setup_events_test: Reached _CANInit");
      --
      loop
        wait for 1 ic;
        if PC == noFreeCh then
          report("flim_setup_events_test: Unexpectedly reached noFreeCh");
          test_state := fail;
          wait for 1 ic;
        end if;
        exit when PC == setid;
      end loop;
      report("flim_setup_events_test: Reached setid");
      --
      wait until PC == main0;
      report("flim_setup_events_test: Reached main0");
      --
      if test_state == pass then
        report("flim_setup_events_test: PASS");
      else
        report("flim_setup_events_test: FAIL");
        report(PC); -- Crashes simulator, MDB will report current source line
      end if;          
      PC <= 0;
      wait;
    end process flim_setup_events_test;
end testbench;
