configuration for "PIC18F2480" is
end configuration;
--
testbench for "PIC18F2480" is
begin
  test_timeout: process is
    begin
      wait for 777 ms;
      report("flim_query_test: TIMEOUT");
      report(PC); -- Crashes simulator, MDB will report current source line
      PC <= 0;
      wait;
    end process test_timeout;
    --
  flim_query_test: process is
    type test_result is (pass, fail);
    variable test_state : test_result;
    begin
      report("flim_query_test: START");
      test_state := pass;
      RA3 <= '1'; -- Setup button not pressed
      RB4 <= '1'; -- Learn off
      RA5 <= '1'; -- Unlearn off
      --
      wait until RB6 == '1'; -- Booted into FLiM
      --
      RXB0D0 <= 16#0D#; -- QNN, CBUS Query node request
      RXB0D1 <= 0;      -- NN high
      RXB0D2 <= 0;      -- NN low
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      --
      wait until TXB1CON.TXREQ == '1';
      if TXB1D0 != 16#B6# then -- PNN, CBUS Query node response
        report("flim_query_test: Sent wrong response");
        test_state := fail;
      end if;
      if TXB1D1 != 4 then
        report("flim_query_test: Sent wrong Node Number (high)");
        test_state := fail;
      end if;
      if TXB1D2 != 2 then
        report("flim_query_test: Sent wrong Node Number (low)");
        test_state := fail;
      end if;
      if TXB1D3 != 165 then
        report("flim_query_test: Sent wrong manufacturer id");
        test_state := fail;
      end if;
      if TXB1D4 != 8 then
        report("flim_query_test: Sent wrong module id");
        test_state := fail;
      end if;
      if TXB1D5 != 13 then
        report("flim_query_test: Sent wrong flags");
        test_state := fail;
      end if;
      --
      if test_state == pass then
        report("flim_query_test: PASS");
      else
        report("flim_query_test: FAIL");
      end if;          
      PC <= 0;
      wait;
    end process flim_query_test;
end testbench;
