configuration for "PIC18F2480" is
  shared label _CANInit;
  shared label setup;
  shared label copyEVs;
  shared label initevdata;
  shared label newid_f;
  shared label timload;
  shared label main0;
end configuration;
--
testbench for "PIC18F2480" is
begin
  test_timeout: process is
    begin
      wait for 1000 ms;
      report("setup_flim_test: TIMEOUT");
      report(PC); -- Crashes simulator, MDB will report current source line
      PC <= 0;
      wait;
    end process test_timeout;
    --
  setup_flim_test: process is
    begin
      report("setup_flim_test: START");
      --
      wait until PC == _CANInit;
      report("setup_flim_test: Reached _CANInit");
      --
      accessin("eedata/boot_setup", hex_mode, EEDATA, false);
      --
      wait until PC == setup;
      report("setup_flim_test: Reached setup");
      --
      wait until PC == copyEVs;
      report("setup_flim_test: Reached copyEVs");
      accessin("eedata/no_freechain_0_events", hex_mode, EEDATA, false);
      wait until PC == initevdata;
      report("setup_flim_test: Reached initevdata");
      --
      accessin("eedata/modstat_flim", hex_mode, EEDATA, false);
      --
      wait until PC == newid_f;
      report("setup_flim_test: Reached newid_f");
      accessin("eedata/default_canid_nodeid", dec_mode, EEDATA, false);
      --
      wait until PC == timload;
      report("setup_flim_test: Reached timload");
      accessin("eedata/default_nv", dec_mode, EEDATA, false);
      --
      wait until PC == main0;
      report("setup_flim_test: Reached main0");
      --
      if RB6 == '0' then
        report("setup_flim_test: FAIL Yellow LED (FLiM) off");
        PC <= 0;
        wait;
      end if;
      if RB7 == '1' then
        report("setup_flim_test: FAIL Green LED (SLiM) on");
        PC <= 0;
        wait;
      end if;
      --
      report("setup_flim_test: PASS");
      PC <= 0;
      wait;
    end process setup_flim_test;
end testbench;
