configuration for "PIC18F2480" is
  shared label _CANInit;
  shared label setup;
  shared label copyEVs;
  shared label initevdata;
  shared label slimset;
  shared label nv_rest;
  shared label timload;
  shared label main0;
end configuration;
--
testbench for "PIC18F2480" is
begin
  test_timeout: process is
    begin
      wait for 2000 ms;
      report("setup_slim_init_test: TIMEOUT");
      report(PC); -- Crashes simulator, MDB will report current source line
      PC <= 0;
      wait;
    end process test_timeout;
    --
  setup_slim_init_test: process is
    type test_result is (pass, fail);
    variable test_state : test_result;
    begin
      report("setup_slim_init_test: START");
      test_state := pass;
      --
      wait until PC == _CANInit;
      report("setup_slim_init_test: Reached _CANInit");
      --
      wait until PC == setup;
      report("setup_slim_init_test: Reached setup");
      --
      wait until PC == copyEVs;
      report("setup_slim_init_test: Reached copyEVs");
      wait until PC == initevdata;
      report("setup_slim_init_test: Reached initevdata");
      --
      wait until PC == slimset;
      report("setup_slim_init_test: Reached slimset");
      --
      RB4 <= '1'; -- DOLEARN off
      RA5 <= '1'; -- UNLEARN off
      --
      wait until PC == nv_rest;
      report("setup_slim_init_test: Reached nv_rest");
      --
      wait until PC == timload;
      report("setup_slim_init_test: Reached timload");
      --
      wait until PC == main0;
      report("setup_slim_init_test: Reached main0");
      --
      if RB6 == '1' then
        report("setup_slim_init_test: Yellow LED (FLiM) on");
        test_state := fail;
      end if;
      if RB7 == '0' then
        report("setup_slim_init_test: Green LED (SLiM) off");
        test_state := fail;
      end if;
      --
      if test_state == pass then
        report("setup_slim_init_test: PASS");
      else
        report("setup_slim_init_test: FAIL");
        report(PC); -- Crashes simulator, MDB will report current source line
      end if;          
      PC <= 0;
      wait;
    end process setup_slim_init_test;
end testbench;
