configuration for "PIC18F2480" is
end configuration;
--
testbench for "PIC18F2480" is
begin
  test_timeout: process is
    begin
      wait for 17265 ms;
      report("slim_boot_with_events_test: TIMEOUT");
      report(PC); -- Crashes simulator, MDB will report current source line
      PC <= 0;
      wait;
    end process test_timeout;
    --
  slim_boot_with_events_test: process is
    type test_result is (pass, fail);
    variable test_state : test_result;
    begin
      report("slim_boot_with_events_test: START");
      test_state := pass;
      RA3 <= '1'; -- Setup button not pressed
      RB4 <= '1'; -- DOLEARN off
      RA5 <= '1'; -- UNLEARN off
      --
      wait until RB7 == '1'; -- Booted into SLiM
      report("slim_boot_with_events_test: Green LED (SLiM) on");
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      report("flim_clear_test: Check long on 0x0102,0x0402");
      RXB0D0 <= 16#90#;    -- ACON, CBUS accessory long on
      RXB0D1 <= 1;         -- NN high
      RXB0D2 <= 2;         -- NN low
      RXB0D3 <= 4;
      RXB0D4 <= 2;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      --
      wait until PORTC != 0;
      if PORTC == 16#40# then -- Output 2B on
        report("slim_boot_with_events_test: 2B triggered");
      else
        report("slim_boot_with_events_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      wait until PORTC != 0;
      if PORTC == 16#20# then -- Output 3A on
        report("slim_boot_with_events_test: 3A triggered");
      else
        report("slim_boot_with_events_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      wait on PORTC for 1005 ms;
      if PORTC != 0 then
        report("slim_boot_with_events_test: Unexpected trigger");
        test_state := fail;
        wait until PORTC == 0;
      end if;
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      report("slim_boot_with_events_test: Check short on 0x0900x0204");
      RXB0D0 <= 16#98#;    -- ACON, CBUS accessory short on
      RXB0D1 <= 9;         -- NN high
      RXB0D2 <= 0;         -- NN low
      RXB0D3 <= 2;
      RXB0D4 <= 4;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      --
      wait until PORTC != 0;
      if PORTC == 16#20# then -- Output 3A on
        report("slim_boot_with_events_test: 3A triggered");
      else
        report("slim_boot_with_events_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      wait on PORTC for 1005 ms;
      if PORTC != 0 then
        report("slim_boot_with_events_test: Unexpected trigger");
        test_state := fail;
        wait until PORTC == 0;
      end if;
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      report("slim_boot_with_events_test: Check long on 0x0102,0x0204");
      RXB0D0 <= 16#90#;    -- ACON, CBUS accessory long on
      RXB0D1 <= 1;         -- NN high
      RXB0D2 <= 2;         -- NN low
      RXB0D3 <= 2;
      RXB0D4 <= 4;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      --
      wait until PORTC != 0;
      if PORTC == 16#04# then -- Output 3B on
        report("slim_boot_with_events_test: 3B triggered");
      else
        report("slim_boot_with_events_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      wait on PORTC for 1005 ms;
      if PORTC != 0 then
        report("slim_boot_with_events_test: Unexpected trigger");
        test_state := fail;
        wait until PORTC == 0;
      end if;
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      report("slim_boot_with_events_test: Check short on 0x0009,0x0402");
      RXB0D0 <= 16#98#;    -- ACON, CBUS accessory short on
      RXB0D1 <= 0;         -- NN high
      RXB0D2 <= 9;         -- NN low
      RXB0D3 <= 4;
      RXB0D4 <= 2;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      --
      wait until PORTC != 0;
      if PORTC == 16#02# then -- Output 2A on
        report("slim_boot_with_events_test: 2A triggered");
      else
        report("slim_boot_with_events_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      wait until PORTC != 0;
      if PORTC == 16#04# then -- Output 3B on
        report("slim_boot_with_events_test: 3B triggered");
      else
        report("slim_boot_with_events_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      wait on PORTC for 1005 ms;
      if PORTC != 0 then
        report("slim_boot_with_events_test: Unexpected trigger");
        test_state := fail;
        wait until PORTC == 0;
      end if;
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      report("slim_boot_with_events_test: Check long on 0x0201,0x0604");
      RXB0D0 <= 16#90#;    -- ACON, CBUS accessory long on
      RXB0D1 <= 2;         -- NN high
      RXB0D2 <= 1;         -- NN low
      RXB0D3 <= 6;
      RXB0D4 <= 4;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      --
      wait until PORTC != 0;
      if PORTC == 16#02# then -- Output 2A on
        report("slim_boot_with_events_test: 2A triggered");
      else
        report("slim_boot_with_events_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      wait on PORTC for 1005 ms;
      if PORTC != 0 then
        report("slim_boot_with_events_test: Unexpected trigger");
        test_state := fail;
        wait until PORTC == 0;
      end if;
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      report("slim_boot_with_events_test: Check long off 0x0102,0x0402");
      RXB0D0 <= 16#91#;    -- ACON, CBUS accessory long off
      RXB0D1 <= 1;         -- NN high
      RXB0D2 <= 2;         -- NN low
      RXB0D3 <= 4;
      RXB0D4 <= 2;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      --
      wait until PORTC != 0;
      if PORTC == 16#02# then -- Output 2A on
        report("slim_boot_with_events_test: 2A triggered");
      else
        report("slim_boot_with_events_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      wait until PORTC != 0;
      if PORTC == 16#04# then -- Output 3B on
        report("slim_boot_with_events_test: 3B triggered");
      else
        report("slim_boot_with_events_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      wait on PORTC for 1005 ms;
      if PORTC != 0 then
        report("slim_boot_with_events_test: Unexpected trigger");
        test_state := fail;
        wait until PORTC == 0;
      end if;
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      report("slim_boot_with_events_test: Check short off 0x0807,0x0204");
      RXB0D0 <= 16#99#;    -- ACON, CBUS accessory short off
      RXB0D1 <= 8;         -- NN high
      RXB0D2 <= 7;         -- NN low
      RXB0D3 <= 2;
      RXB0D4 <= 4;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      --
      wait until PORTC != 0;
      if PORTC == 16#04# then -- Output 3B on
        report("slim_boot_with_events_test: 3B triggered");
      else
        report("slim_boot_with_events_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      wait on PORTC for 1005 ms;
      if PORTC != 0 then
        report("slim_boot_with_events_test: Unexpected trigger");
        test_state := fail;
        wait until PORTC == 0;
      end if;
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      report("slim_boot_with_events_test: Long off 0x0201,0x0604");
      RXB0D0 <= 16#91#;    -- ACON, CBUS accessory long off
      RXB0D1 <= 2;         -- NN high
      RXB0D2 <= 1;         -- NN low
      RXB0D3 <= 6;
      RXB0D4 <= 4;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      --
      wait until PORTC != 0;
      if PORTC == 16#40# then -- Output 2B on
        report("slim_boot_with_events_test: 2B triggered");
      else
        report("slim_boot_with_events_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      wait on PORTC for 1005 ms;
      if PORTC != 0 then
        report("slim_boot_with_events_test: Unexpected trigger");
        test_state := fail;
        wait until PORTC == 0;
      end if;
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      report("slim_boot_with_events_test: Check long off 0x0102,0x0204");
      RXB0D0 <= 16#90#;    -- ACON, CBUS accessory long off
      RXB0D1 <= 1;         -- NN high
      RXB0D2 <= 2;         -- NN low
      RXB0D3 <= 2;
      RXB0D4 <= 4;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      --
      wait until PORTC != 0;
      if PORTC == 16#04# then -- Output 3B on
        report("slim_boot_with_events_test: 3B triggered");
      else
        report("slim_boot_with_events_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      wait on PORTC for 1005 ms;
      if PORTC != 0 then
        report("slim_boot_with_events_test: Unexpected trigger");
        test_state := fail;
        wait until PORTC == 0;
      end if;
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      report("slim_boot_with_events_test: Check short off 0x0605,0x0402");
      RXB0D0 <= 16#99#;    -- ACON, CBUS accessory short off
      RXB0D1 <= 6;         -- NN high
      RXB0D2 <= 5;         -- NN low
      RXB0D3 <= 4;
      RXB0D4 <= 2;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      --
      wait until PORTC != 0;
      if PORTC == 16#40# then -- Output 2B on
        report("slim_boot_with_events_test: 2B triggered");
      else
        report("slim_boot_with_events_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      wait until PORTC != 0;
      if PORTC == 16#20# then -- Output 3A on
        report("slim_boot_with_events_test: 3A triggered");
      else
        report("slim_boot_with_events_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      wait on PORTC for 1005 ms;
      if PORTC != 0 then
        report("slim_boot_with_events_test: Unexpected trigger");
        test_state := fail;
        wait until PORTC == 0;
      end if;
      --
      if test_state == pass then
        report("slim_boot_with_events_test: PASS");
      else
        report("slim_boot_with_events_test: FAIL");
      end if;          
      PC <= 0;
      wait;
    end process slim_boot_with_events_test;
end testbench;
