configuration for "PIC18F2480" is
end configuration;
--
testbench for "PIC18F2480" is
begin
  test_timeout: process is
    begin
      wait for 11000 ms;
      report("slim_learn_normal_test: TIMEOUT");
      report(PC); -- Crashes simulator, MDB will report current source line
      PC <= 0;
      wait;
    end process test_timeout;
    --
  slim_learn_normal_test: process is
    type test_result is (pass, fail);
    variable test_state : test_result;
    variable event_high : integer;
    variable event_low : integer;
    begin
      report("slim_learn_normal_test: START");
      test_state := pass;
      RA3 <= '1'; -- Setup button not pressed
      RB4 <= '1'; -- Learn off
      RA5 <= '1'; -- Unlearn off
      --
      wait until RB7 == '1'; -- Booted into SLiM
      --
      RXB0D0 <= 16#90#;    -- ACON, CBUS accessory on
      RXB0D1 <= 0;         -- NN high
      RXB0D2 <= 0;         -- NN low
      RXB0D3 <= 4;
      RXB0D4 <= 2;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_normal_test: On event 0x0402 to be ignored");
      --
      wait on PORTC for 5 ms;
      if PORTC != 0 then
        report("slim_learn_normal_test: Unexpected trigger");
        test_state := fail;
      end if;
      --
      -- Learn events for output 3
      RB4 <= '0'; -- Learn on
      RB0 <= '0'; -- Sel 0 on
      RB1 <= '1'; -- Sel 1 off
      RB5 <= '1'; -- Polarity normal, On event => A, Off event => B
      --
      RXB0D0 <= 16#90#;    -- ACON, CBUS accessory on
      RXB0D1 <= 0;         -- NN high
      RXB0D2 <= 0;         -- NN low
      RXB0D3 <= 4;
      RXB0D4 <= 2;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_normal_test: On event 0x0402 to be learnt for 3A");
      --
      wait on PORTC;
      if PORTC == 16#20# then -- Output 3A on
        report("slim_learn_normal_test: 3A triggered");
      else
        report("slim_learn_normal_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait on PORTC;
      if PORTC != 0 then
        report("slim_learn_normal_test: Output not turned off");
        test_state := fail;
      end if;
      --
      RXB0D0 <= 16#91#;    -- ACON, CBUS accessory off
      RXB0D1 <= 0;         -- NN high
      RXB0D2 <= 0;         -- NN low
      RXB0D3 <= 2;
      RXB0D4 <= 4;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_normal_test: Off event 0x0204 to be learnt for 3B");
      --
      wait on PORTC;
      if PORTC == 16#04# then -- Output 3B on
        report("slim_learn_normal_test: 3B triggered");
      else
        report("slim_learn_normal_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait on PORTC;
      if PORTC != 0 then
        report("slim_learn_normal_test: Output not turned off");
        test_state := fail;
      end if;
      --
      -- Learn events for output 2
      RB4 <= '0'; -- Learn on
      RB0 <= '1'; -- Sel 0 off
      RB1 <= '0'; -- Sel 1 on
      RB5 <= '1'; -- Polarity normal, On event => A, Off event => B
      --
      RXB0D0 <= 16#90#;    -- ACON, CBUS accessory on
      RXB0D1 <= 0;         -- NN high
      RXB0D2 <= 0;         -- NN low
      RXB0D3 <= 4;
      RXB0D4 <= 2;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_normal_test: On event 0x0402 to be learnt for 2A");
      --
      wait on PORTC;
      if PORTC == 16#02# then -- Output 2A on
        report("slim_learn_normal_test: 2A triggered");
      else
        report("slim_learn_normal_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait on PORTC;
      if PORTC != 0 then
        report("slim_learn_normal_test: Output not turned off");
        test_state := fail;
      end if;
      --
      RB4 <= '1'; -- Learn off
      --
      RXB0D0 <= 16#90#;    -- ACON, CBUS accessory on
      RXB0D1 <= 0;         -- NN high
      RXB0D2 <= 0;         -- NN low
      RXB0D3 <= 2;
      RXB0D4 <= 2;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_normal_test: On event 0x0202 to be ignored");
      --
      wait on PORTC for 5 ms;
      if PORTC != 0 then
        report("slim_learn_normal_test: Unexpected trigger");
        test_state := fail;
      end if;
      --
      RXB0D0 <= 16#90#;    -- ACON, CBUS accessory on
      RXB0D1 <= 0;         -- NN high
      RXB0D2 <= 0;         -- NN low
      RXB0D3 <= 4;
      RXB0D4 <= 2;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_normal_test: On event 0x0402 trigger 2A then 3A");
      --
      wait on PORTC;
      if PORTC == 16#02# then -- Output 2A on
        report("slim_learn_normal_test: 2A triggered");
      else
        report("slim_learn_normal_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait on PORTC;
      if PORTC != 0 then
        report("slim_learn_normal_test: Output not turned off");
        test_state := fail;
      end if;
      --
      wait on PORTC;
      if PORTC == 16#20# then -- Output 3A on
        report("slim_learn_normal_test: 3A triggered");
      else
        report("slim_learn_normal_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait on PORTC;
      if PORTC != 0 then
        report("slim_learn_normal_test: Output not turned off");
        test_state := fail;
      end if;
      --
      wait on PORTC for 5 ms;
      if PORTC != 0 then
        report("slim_learn_normal_test: Unexpected trigger");
        test_state := fail;
      end if;
      --
      RXB0D0 <= 16#91#;    -- ACON, CBUS accessory off
      RXB0D1 <= 0;         -- NN high
      RXB0D2 <= 0;         -- NN low
      RXB0D3 <= 4;
      RXB0D4 <= 2;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_normal_test: Off event 0x0402 trigger 2B then 3B");
      --
      wait on PORTC;
      if PORTC == 16#40# then -- Output 2B on
        report("slim_learn_normal_test: 2B triggered");
      else
        report("slim_learn_normal_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait on PORTC;
      if PORTC != 0 then
        report("slim_learn_normal_test: Output not turned off");
        test_state := fail;
      end if;
      --
      wait on PORTC;
      if PORTC == 16#04# then -- Output 3B on
        report("slim_learn_normal_test: 3B triggered");
      else
        report("slim_learn_normal_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait on PORTC;
      if PORTC != 0 then
        report("slim_learn_normal_test: Output not turned off");
        test_state := fail;
      end if;
      --
      wait on PORTC for 5 ms;
      if PORTC != 0 then
        report("slim_learn_normal_test: Unexpected trigger");
        test_state := fail;
      end if;
      --
      RXB0D0 <= 16#90#;    -- ACON, CBUS accessory on
      RXB0D1 <= 0;         -- NN high
      RXB0D2 <= 0;         -- NN low
      RXB0D3 <= 2;
      RXB0D4 <= 4;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_normal_test: On event 0x0204 trigger 3A");
      --
      wait on PORTC;
      if PORTC == 16#20# then -- Output 3A on
        report("slim_learn_normal_test: 3A triggered");
      else
        report("slim_learn_normal_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait on PORTC;
      if PORTC != 0 then
        report("slim_learn_normal_test: Output not turned off");
        test_state := fail;
      end if;
      --
      wait on PORTC for 5 ms;
      if PORTC != 0 then
        report("slim_learn_normal_test: Unexpected trigger");
        test_state := fail;
      end if;
      --
      RXB0D0 <= 16#91#;    -- ACON, CBUS accessory off
      RXB0D1 <= 0;         -- NN high
      RXB0D2 <= 0;         -- NN low
      RXB0D3 <= 2;
      RXB0D4 <= 4;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_normal_test: Off event 0x0204 trigger 3B");
      --
      wait on PORTC;
      if PORTC == 16#04# then -- Output 3B on
        report("slim_learn_normal_test: 3B triggered");
      else
        report("slim_learn_normal_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait on PORTC;
      if PORTC != 0 then
        report("slim_learn_normal_test: Output not turned off");
        test_state := fail;
      end if;
      --
      wait on PORTC for 5 ms;
      if PORTC != 0 then
        report("slim_learn_normal_test: Unexpected trigger");
        test_state := fail;
      end if;
      --
      RXB0D0 <= 16#90#;    -- ACON, CBUS accessory on
      RXB0D1 <= 0;         -- NN high
      RXB0D2 <= 0;         -- NN low
      RXB0D3 <= 2;
      RXB0D4 <= 2;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_normal_test: On event 0x0202 to be ignored");
      --
      wait on PORTC for 5 ms;
      if PORTC != 0 then
        report("slim_learn_normal_test: Unexpected trigger");
        test_state := fail;
      end if;
      --
      if test_state == pass then
        report("slim_learn_normal_test: PASS");
      else
        report("slim_learn_normal_test: FAIL");
      end if;          
      PC <= 0;
      wait;
    end process slim_learn_normal_test;
end testbench;
