configuration for "PIC18F2480" is
end configuration;
--
testbench for "PIC18F2480" is
begin
  test_timeout: process is
    begin
      wait for 2000 ms;
      report("slim_invalid_param_test: TIMEOUT");
      PC <= 0;
      wait;
    end process test_timeout;
    --
  slim_invalid_param_test: process is
    type test_result is (pass, fail);
    variable test_state : test_result;
    variable bad_index : integer;
    begin
      report("slim_invalid_param_test: START");
      test_state := pass;
      RA3 <= '1';
      bad_index := 15; -- Invalid parameter index, only 14 parameters
      --
      wait until RB7 == '1'; -- Booted into SLiM
      --
      RXB0D0 <= 16#73#;    -- CBUS param request
      RXB0D1 <= 0;         -- NN high
      RXB0D2 <= 0;         -- NN low
      RXB0D3 <= bad_index; -- Parameter index
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      --
      wait until TXB1CON.TXREQ == '1';
      if TXB1D0 != 16#6F# then
        report("slim_invalid_param_test: Sent wrong response");
        test_state := fail;
      end if;
      if TXB1D1 != 0 then
        report("slim_invalid_param_test: Sent wrong Node Number (high)");
        test_state := fail;
      end if;
      if TXB1D2 != 0 then
        report("slim_invalid_param_test: Sent wrong Node Number (low)");
        test_state := fail;
      end if;
      if TXB1D3 != 10 then
        report("slim_invalid_param_test: Sent wrong error number");
        test_state := fail;
      end if;
      --
      if test_state == pass then
        report("slim_invalid_param_test: PASS");
      else
        report("slim_invalid_param_test: FAIL");
      end if;          
      PC <= 0;
      wait;
    end process slim_invalid_param_test;
end testbench;
