configuration for "PIC18F2480" is
end configuration;
--
testbench for "PIC18F2480" is
begin
  test_timeout: process is
    begin
      wait for 13715 ms;
      report("slim_learn_mixed_test: TIMEOUT");
      report(PC); -- Crashes simulator, MDB will report current source line
      PC <= 0;
      wait;
    end process test_timeout;
    --
  slim_learn_mixed_test: process is
    type test_result is (pass, fail);
    variable test_state : test_result;
    variable event_high : integer;
    variable event_low : integer;
    begin
      report("slim_learn_mixed_test: START");
      test_state := pass;
      RA3 <= '1'; -- Setup button not pressed
      RB4 <= '1'; -- Learn off
      RA5 <= '1'; -- Unlearn off
      --
      wait until RB7 == '1'; -- Booted into SLiM
      --
      -- Learn events for output 3
      RB4 <= '0'; -- Learn on
      RB0 <= '0'; -- Sel 0 on
      RB1 <= '1'; -- Sel 1 off
      RB5 <= '1'; -- Polarity normal
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      RXB0D0 <= 16#90#;    -- ACON, CBUS accessory on
      RXB0D1 <= 1;         -- NN high
      RXB0D2 <= 2;         -- NN low
      RXB0D3 <= 4;
      RXB0D4 <= 2;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_mixed_test: Learn on event 0x0402 for 3A");
      --
      wait until PORTC != 0;
      if PORTC == 16#20# then -- Output 3A on
        report("slim_learn_mixed_test: 3A triggered");
      else
        report("slim_learn_mixed_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      RB5 <= '0'; -- Polarity inverse
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      RXB0D0 <= 16#98#;    -- ACON, CBUS accessory short on
      RXB0D1 <= 2;         -- NN high
      RXB0D2 <= 1;         -- NN low
      RXB0D3 <= 2;
      RXB0D4 <= 4;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_mixed_test: Learn short on event 0x0204 for 3B");
      --
      wait until PORTC != 0;
      if PORTC == 16#04# then -- Output 3B on
        report("slim_learn_mixed_test: 3B triggered");
      else
        report("slim_learn_mixed_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      -- Learn events for output 2
      RB4 <= '0'; -- Learn on
      RB0 <= '1'; -- Sel 0 off
      RB1 <= '0'; -- Sel 1 on
      RB5 <= '1'; -- Polarity normal
      --
      -- * NB **************************************************************
      -- * Should be able to use opposite versions of events for 3A and 3B *
      -- * but that's not working so for now use unique event numbers.     *
      -- *******************************************************************
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      RXB0D0 <= 16#91#;    -- ACON, CBUS accessory off
      RXB0D1 <= 2;         -- NN high
      RXB0D2 <= 1;         -- NN low
      RXB0D3 <= 6;
      RXB0D4 <= 4;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_mixed_test: Learn off event 0x0604 for 2B");
      --
      wait until PORTC != 0;
      if PORTC == 16#40# then -- Output 2B on
        report("slim_learn_mixed_test: 2B triggered");
      else
        report("slim_learn_mixed_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      RB5 <= '0'; -- Polarity inverse
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      RXB0D0 <= 16#99#;    -- ACON, CBUS accessory short off
      RXB0D1 <= 1;         -- NN high
      RXB0D2 <= 2;         -- NN low
      RXB0D3 <= 4;
      RXB0D4 <= 6;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_mixed_test: Learn short off event 0x0406 for 2A");
      --
      wait until PORTC != 0;
      if PORTC == 16#02# then -- Output 2A on
        report("slim_learn_mixed_test: 2A triggered");
      else
        report("slim_learn_mixed_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      RB4 <= '1'; -- Learn off
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      RXB0D0 <= 16#98#;    -- ACON, CBUS accessory short on
      RXB0D1 <= 1;         -- NN high
      RXB0D2 <= 2;         -- NN low
      RXB0D3 <= 4;
      RXB0D4 <= 2;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_mixed_test: Short on event 0x0402 ignored");
      --
      wait on PORTC for 1005 ms;
      if PORTC != 0 then
        report("slim_learn_mixed_test: Unexpected trigger");
        test_state := fail;
        wait until PORTC == 0;
      end if;
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      RXB0D0 <= 16#90#;    -- ACON, CBUS accessory on
      RXB0D1 <= 1;         -- NN high
      RXB0D2 <= 2;         -- NN low
      RXB0D3 <= 4;
      RXB0D4 <= 2;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_mixed_test: On event 0x0402 trigger 3A");
      --
      wait until PORTC != 0;
      if PORTC == 16#20# then -- Output 3A on
        report("slim_learn_mixed_test: 3A triggered");
      else
        report("slim_learn_mixed_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      wait on PORTC for 1005 ms;
      if PORTC != 0 then
        report("slim_learn_mixed_test: Unexpected trigger");
        test_state := fail;
        wait until PORTC == 0;
      end if;
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      RXB0D0 <= 16#90#;    -- ACON, CBUS accessory on
      RXB0D1 <= 2;         -- NN high
      RXB0D2 <= 1;         -- NN low
      RXB0D3 <= 2;
      RXB0D4 <= 4;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_mixed_test: On event 0x0204 ignored");
      --
      wait on PORTC for 1005 ms;
      if PORTC != 0 then
        report("slim_learn_mixed_test: Unexpected trigger");
        test_state := fail;
        wait until PORTC == 0;
      end if;
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      RXB0D0 <= 16#98#;    -- ACON, CBUS accessory short on
      RXB0D1 <= 5;         -- NN high
      RXB0D2 <= 6;         -- NN low
      RXB0D3 <= 2;
      RXB0D4 <= 4;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_mixed_test: Short on event 0x0204 trigger 3B");
      --
      wait until PORTC != 0;
      if PORTC == 16#04# then -- Output 3B on
        report("slim_learn_mixed_test: 3B triggered");
      else
        report("slim_learn_mixed_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      wait on PORTC for 1005 ms;
      if PORTC != 0 then
        report("slim_learn_mixed_test: Unexpected trigger");
        test_state := fail;
        wait until PORTC == 0;
      end if;
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      RXB0D0 <= 16#91#;    -- ACON, CBUS accessory off
      RXB0D1 <= 1;         -- NN high
      RXB0D2 <= 2;         -- NN low
      RXB0D3 <= 4;
      RXB0D4 <= 6;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_mixed_test: Off event 0x0406 ignored");
      --
      wait on PORTC for 1005 ms;
      if PORTC != 0 then
        report("slim_learn_mixed_test: Unexpected trigger");
        test_state := fail;
        wait until PORTC == 0;
      end if;
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      RXB0D0 <= 16#99#;    -- ACON, CBUS accessory short off
      RXB0D1 <= 7;         -- NN high
      RXB0D2 <= 8;         -- NN low
      RXB0D3 <= 4;
      RXB0D4 <= 6;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_mixed_test: Short off event 0x0406 trigger 2A");
      --
      wait until PORTC != 0;
      if PORTC == 16#02# then -- Output 2A on
        report("slim_learn_mixed_test: 2A triggered");
      else
        report("slim_learn_mixed_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      wait on PORTC for 1005 ms;
      if PORTC != 0 then
        report("slim_learn_mixed_test: Unexpected trigger");
        test_state := fail;
        wait until PORTC == 0;
      end if;
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      RXB0D0 <= 16#99#;    -- ACON, CBUS accessory short off
      RXB0D1 <= 2;         -- NN high
      RXB0D2 <= 1;         -- NN low
      RXB0D3 <= 6;
      RXB0D4 <= 4;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_mixed_test: Short off event 0x0604 ignored");
      --
      wait on PORTC for 1005 ms;
      if PORTC != 0 then
        report("slim_learn_mixed_test: Unexpected trigger");
        test_state := fail;
        wait until PORTC == 0;
      end if;
      --
      if RXB0CON.RXFUL != '0' then
        wait until RXB0CON.RXFUL == '0';
      end if;
      RXB0D0 <= 16#91#;    -- ACON, CBUS accessory off
      RXB0D1 <= 2;         -- NN high
      RXB0D2 <= 1;         -- NN low
      RXB0D3 <= 6;
      RXB0D4 <= 4;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      report("slim_learn_mixed_test: Off event 0x0604 trigger 2B");
      --
      wait until PORTC != 0;
      if PORTC == 16#40# then -- Output 2B on
        report("slim_learn_mixed_test: 2B triggered");
      else
        report("slim_learn_mixed_test: Wrong output");
        test_state := fail;
      end if;
      --
      wait until PORTC == 0;
      --
      wait on PORTC for 1005 ms;
      if PORTC != 0 then
        report("slim_learn_mixed_test: Unexpected trigger");
        test_state := fail;
      end if;
      --
      if test_state == pass then
        report("slim_learn_mixed_test: PASS");
      else
        report("slim_learn_mixed_test: FAIL");
      end if;          
      PC <= 0;
      wait;
    end process slim_learn_mixed_test;
end testbench;
