configuration for "PIC18F2480" is
  shared variable Datmode;
end configuration;
--
testbench for "PIC18F2480" is
begin
  test_timeout: process is
    begin
      wait for 2000 ms;
      report("slim_params_test: TIMEOUT");
      PC <= 0;
      wait;
    end process test_timeout;
    --
  slim_params_test: process is
    type test_result is (pass, fail);
    variable test_state : test_result;
    begin
      report("slim_params_test: START");
      test_state := pass;
      RA3 <= '1'; -- Setup button not pressed
      --
      wait until RB7 == '1'; -- Booted into SLiM
      --
      RXB0D0 <= 16#10#; -- CBUS all params request
      RXB0D1 <= 0;      -- NN high
      RXB0D2 <= 0;      -- NN low
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      Datmode <= 4;     -- Request only valid when switching to FLiM
      --
      wait until TXB1CON.TXREQ == '1';
      if TXB1D0 != 16#EF# then
        report("slim_params_test: Sent wrong response");
        test_state := fail;
      end if;
      if TXB1D1 != 165 then
        report("slim_params_test: Sent wrong manufacturer id");
        test_state := fail;
      end if;
      if TXB1D2 != 81 then -- Q
        report("slim_params_test: Sent wrong minor version");
        test_state := fail;
      end if;
      if TXB1D3 != 8 then
        report("slim_params_test: Sent wrong module id");
        test_state := fail;
      end if;
      if TXB1D4 != 128 then
        report("slim_params_test: Sent wrong number of events allowed");
        test_state := fail;
      end if;
      if TXB1D5 != 2 then
        report("slim_params_test: Sent wrong number of variables per event");
        test_state := fail;
      end if;
      if TXB1D6 != 16 then
        report("slim_params_test: Sent wrong number of node variables");
        test_state := fail;
      end if;
      if TXB1D7 != 2 then
        report("slim_params_test: Sent wrong major version");
        test_state := fail;
      end if;
      --
      if test_state == pass then
        report("slim_params_test: PASS");
      else
        report("slim_params_test: FAIL");
      end if;          
      PC <= 0;
      wait;
    end process slim_params_test;
end testbench;
