configuration for "PIC18F2480" is
  shared label noFreeCh;
end configuration;
--
testbench for "PIC18F2480" is
begin
  test_timeout: process is
    begin
      wait for 2000 ms;
      report("slim_boot_learn_test: TIMEOUT");
      report(PC); -- Crashes simulator, MDB will report current source line
      PC <= 0;
      wait;
    end process test_timeout;
    --
  slim_boot_learn_test: process is
    type test_result is (pass, fail);
    variable test_state : test_result;
    begin
      report("slim_boot_learn_test: START");
      test_state := pass;
      RA3 <= '1'; -- Setup button not pressed
      --
      RB4 <= '0'; -- DOLEARN on
      RA5 <= '1'; -- UNLEARN off
      --
      loop
        wait for 1 ic;
        if PC == noFreeCh then -- Test for initialising event store
          report("slim_boot_learn_test: Unexpectedly reached noFreeCh");
          test_state := fail;
        end if;
        exit when RB7 == '1'; -- Booted into SLiM
      end loop;
      report("slim_boot_learn_test: Green LED (SLiM) on");
      --
      if test_state == pass then
        report("slim_boot_learn_test: PASS");
      else
        report("slim_boot_learn_test: FAIL");
      end if;          
      PC <= 0;
      wait;
    end process slim_boot_learn_test;
end testbench;
