configuration for "PIC18F2480" is
  shared label noFreeCh;
end configuration;
--
testbench for "PIC18F2480" is
begin
  test_timeout: process is
    begin
      wait for 2000 ms;
      report("slim_boot_init_test: TIMEOUT");
      report(PC); -- Crashes simulator, MDB will report current source line
      PC <= 0;
      wait;
    end process test_timeout;
    --
  slim_boot_init_test: process is
    type test_result is (pass, fail);
    variable test_state : test_result;
    begin
      report("slim_boot_init_test: START");
      test_state := pass;
      RA3 <= '1'; -- Setup button not pressed
      RB4 <= '1'; -- DOLEARN off
      RA5 <= '1'; -- UNLEARN off
      --
      wait until PC == noFreeCh; -- Initialise event store
      report("slim_boot_init_test: Reached noFreeCh");
      --
      wait until RB7 == '1'; -- Booted into SLiM
      report("slim_boot_init_test: Green LED (SLiM) on");
      --
      if test_state == pass then
        report("slim_boot_init_test: PASS");
      else
        report("slim_boot_init_test: FAIL");
        report(PC); -- Crashes simulator, MDB will report current source line
      end if;          
      PC <= 0;
      wait;
    end process slim_boot_init_test;
end testbench;
