configuration for "PIC18F2480" is
  shared label slimset;
  shared label initevdata;
  shared label mains;
end configuration;
--
testbench for "PIC18F2480" is
begin
  test_timeout: process is
    begin
      wait for 2000 ms;
      report("slim_ignore_unlearn_boot_test: TIMEOUT");
      report(PC); -- Crashes simulator, MDB will report current source line
      PC <= 0;
      wait;
    end process test_timeout;
    --
  slim_ignore_unlearn_boot_test: process is
    type test_result is (pass, fail);
    variable test_state : test_result;
    begin
      report("slim_ignore_unlearn_boot_test: START");
      test_state := pass;
      RA3 <= '1'; -- Setup button not pressed
      --
      RB4 <= '0'; -- DOLEARN on
      RA5 <= '0'; -- UNLEARN on
      --
      wait until PC == slimset; -- SLiM setup
      report("slim_ignore_unlearn_boot_test: Reached slimset");
      --
      loop
        wait for 1 ic;
        if PC == initevdata then -- Test for initialising event data
          report("slim_ignore_unlearn_boot_test: Unexpectedly reached initevdata");
          test_state := fail;
          wait for 1 ic;
        end if;
        exit when PC == mains; -- SLiM start of main loop
      end loop;
      report("slim_ignore_unlearn_boot_test: Reached mains");
      --
      if test_state == pass then
        report("slim_ignore_unlearn_boot_test: PASS");
      else
        report("slim_ignore_unlearn_boot_test: FAIL");
      end if;          
      PC <= 0;
      wait;
    end process slim_ignore_unlearn_boot_test;
end testbench;
