configuration for "PIC18F2480" is
  shared label _CANInit;
  shared label slimset;
  shared label initevdata;
  shared label mains;
end configuration;
--
testbench for "PIC18F2480" is
begin
  test_timeout: process is
    begin
      wait for 2000 ms;
      report("slim_unlearn_boot_test: TIMEOUT");
      report(PC); -- Crashes simulator, MDB will report current source line
      PC <= 0;
      wait;
    end process test_timeout;
    --
  slim_unlearn_boot_test: process is
    type test_result is (pass, fail);
    variable test_state : test_result;
    begin
      report("slim_unlearn_boot_test: START");
      test_state := pass;
      --
      RB4 <= '1'; -- DOLEARN off
      RA5 <= '0'; -- UNLEARN on
      --
      wait until PC == _CANInit;
      report("slim_unlearn_boot_test: Reached _CANInit");
      --
      wait until PC == slimset;
      report("slim_unlearn_boot_test: Reached slimset");
      --
      wait until PC == initevdata;
      report("slim_unlearn_boot_test: Reached initevdata");
      --
      wait until PC == mains;
      report("slim_unlearn_boot_test: Reached mains");
      --
      if test_state == pass then
        report("slim_unlearn_boot_test: PASS");
      else
        report("slim_unlearn_boot_test: FAIL");
      end if;          
      PC <= 0;
      wait;
    end process slim_unlearn_boot_test;
end testbench;
