configuration for "PIC18F2480" is
  shared label    _CANInit;
  shared label    _CANMain;
end configuration;
--
testbench for "PIC18F2480" is
begin
  test_timeout: process is
    begin
      wait for 2000 ms;
      report("slim_reboot_test: TIMEOUT");
      PC <= 0;
      wait;
    end process test_timeout;
    --
  slim_reboot_test: process is
    type test_result is (pass, fail);
    variable test_state : test_result;
    begin
      report("slim_reboot_test: START");
      test_state := pass;
      RA3 <= '1'; -- Setup button not pressed
      --
      wait until RB7 == '1'; -- Booted into SLiM
      --
      RXB0D0 <= 16#5C#; -- BOOTM, CBUS bootload mode request
      RXB0D1 <= 0;      -- NN high
      RXB0D2 <= 0;      -- NN low
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      --
      wait until RB7 == '0'; -- Wait for LED output reset on reboot
      report("slim_reboot_test: Reboot");
      --
      wait until PC == 0;
      PC <= _CANInit;
      --
      wait until PC == _CANMain;
      report("slim_reboot_test: Reached _CANMain, in bootloader");
      --
      if test_state == pass then
        report("slim_reboot_test: PASS");
      else
        report("slim_reboot_test: FAIL");
      end if;          
      PC <= 0;
      wait;
    end process slim_reboot_test;
end testbench;
