configuration for "PIC18F2480" is
end configuration;
--
testbench for "PIC18F2480" is
begin
  test_timeout: process is
    begin
      wait for 2000 ms;
      report("slim_param_count_test: TIMEOUT");
      PC <= 0;
      wait;
    end process test_timeout;
    --
  slim_param_count_test: process is
    type test_result is (pass, fail);
    variable test_state : test_result;
    variable count_index : integer;
    begin
      report("slim_param_count_test: START");
      test_state := pass;
      RA3 <= '1';
      count_index := 0; -- Index of parameter count
      --
      wait until RB7 == '1';
      RXB0D0 <= 16#73#;
      RXB0D1 <= 0;
      RXB0D2 <= 0;
      RXB0D3 <= count_index;
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      --
      wait until TXB1CON.TXREQ == '1';
      if TXB1D0 != 16#9B# then
        report("slim_param_count_test: Sent wrong response");
        test_state := fail;
      end if;
      if TXB1D1 != 0 then
        report("slim_param_count_test: Sent wrong Node Number (high)");
        test_state := fail;
      end if;
      if TXB1D2 != 0 then
        report("slim_param_count_test: Sent wrong Node Number (low)");
        test_state := fail;
      end if;
      if TXB1D3 != count_index then
        report("slim_param_count_test: Sent wrong parameter index");
        test_state := fail;
      end if;
      if TXB1D4 != 14 then
        report("slim_param_count_test: Sent wrong parameter count");
        test_state := fail;
      end if;
      --
      if test_state == pass then
        report("slim_param_count_test: PASS");
      else
        report("slim_param_count_test: FAIL");
      end if;          
      PC <= 0;
      wait;
    end process slim_param_count_test;
end testbench;
