configuration for "PIC18F2480" is
end configuration;
--
testbench for "PIC18F2480" is
begin
  test_timeout: process is
    begin
      wait for 2000 ms;
      report("slim_reboot_wrong_NNh_test: TIMEOUT");
      PC <= 0;
      wait;
    end process test_timeout;
    --
  slim_reboot_wrong_NNh_test: process is
    type test_result is (pass, fail);
    variable test_state : test_result;
    begin
      report("slim_reboot_wrong_NNh_test: START");
      test_state := pass;
      RA3 <= '1';
      --
      wait until RB7 == '1'; -- Booted into SLiM
      --
      RXB0D0 <= 16#5C#;  -- CBUS reboot request
      RXB0D1 <= 1;       -- NN high
      RXB0D2 <= 0;       -- NN low
      RXB0CON.RXFUL <= '1';
      RXB0DLC.DLC3 <= '1';
      CANSTAT <= 16#0C#;
      PIR3.RXB0IF <= '1';
      --
      wait until RB7 == '0' for 5 ms; -- Test if LED output reset by reboot
      if RB7 == '0' then
        report("slim_reboot_wrong_NNh_test: Unexpected reboot");
        test_state := fail;
      end if;
      --
      if test_state == pass then
        report("slim_reboot_wrong_NNh_test: PASS");
      else
        report("slim_reboot_wrong_NNh_test: FAIL");
      end if;          
      PC <= 0;
      wait;
    end process slim_reboot_wrong_NNh_test;
end testbench;
